apiVersion: v1
kind: Secret
metadata:
  name: pg-database-dsn # Replace with config database name. Note: PG_DATABASE_DSN will be pg-database-dsn
                        # To convert replace _ with - and make it lower case
data:
  dsn: postgres://user:password@host:port/database_name # replace with base64_encoded_dsn
